_README = """# __MODEL_NAME__ — ExecuTorch export

This archive contains an [ExecuTorch](https://pytorch.org/executorch/) build of the
edge-ml model **__MODEL_NAME__** for running on smartphones and other mobile devices.

## Contents

| File | Description |
| --- | --- |
| `model.pte` | The ExecuTorch program (XNNPACK-lowered). Preprocessing (normalization__FEATURES_NOTE__) is baked into the graph. |
| `manifest.json` | Everything the app needs to feed the model: input shape, sensor order, window size/stride, sampling rate and output labels. |
| `ExampleClassifier.kt` | Minimal Kotlin example for Android. |

## How inference works

1. Sample the sensors listed in `manifest.json` → `input.timeseries` (in that exact order)
   at `sampling_rate` Hz.
2. Buffer the last `window.size` samples into a float32 array of shape
   `[1, window.size, channels]` (sample-major: all channel values of sample 0, then
   sample 1, ...). Do **not** include timestamps.
3. Run the model every `window.stride` samples.
4. The output is a logits vector; the index of the largest value is the predicted
   class. Class names are in `output.labels`.

## Android quick start

Add the ExecuTorch Android package to your Gradle dependencies:

```gradle
dependencies {
    implementation("org.pytorch:executorch-android:__EXECUTORCH_VERSION__")
}
```

Then see `ExampleClassifier.kt`. For iOS, use the ExecuTorch Swift package —
the tensor layout described in `manifest.json` is identical.

---
Generated by [edge-ml](https://edge-ml.org). ExecuTorch runtime version used for export: __EXECUTORCH_VERSION__.
"""

_KOTLIN = """import org.pytorch.executorch.EValue
import org.pytorch.executorch.Module
import org.pytorch.executorch.Tensor

/**
 * Minimal example for running the edge-ml model "__MODEL_NAME__" on Android.
 *
 * Feed sensor samples in the order given by manifest.json -> input.timeseries:
 * __TIMESERIES__
 */
class ExampleClassifier(modelPath: String) {

    companion object {
        const val WINDOW_SIZE = __WINDOW_SIZE__
        const val STRIDE = __STRIDE__
        const val CHANNELS = __CHANNELS__
        val LABELS = arrayOf(__LABELS__)
    }

    private val module: Module = Module.load(modelPath)
    private val buffer = FloatArray(WINDOW_SIZE * CHANNELS)
    private var samplesSeen = 0
    private var samplesSinceLast = 0

    /** Call once per sensor sample, values ordered like manifest input.timeseries. */
    fun addDatapoint(values: FloatArray) {
        // shift the window one sample to the left and append the new sample
        System.arraycopy(buffer, CHANNELS, buffer, 0, (WINDOW_SIZE - 1) * CHANNELS)
        System.arraycopy(values, 0, buffer, (WINDOW_SIZE - 1) * CHANNELS, CHANNELS)
        samplesSeen++
        samplesSinceLast++
    }

    /**
     * Returns a fresh predicted label, or null while the window is still filling
     * up or fewer than STRIDE new samples have arrived since the last prediction.
     * Call it after every addDatapoint; it classifies once per STRIDE samples,
     * matching manifest.json -> window.stride.
     */
    fun predict(): String? {
        if (samplesSeen < WINDOW_SIZE || samplesSinceLast < STRIDE) return null
        samplesSinceLast = 0
        val input = Tensor.fromBlob(buffer, longArrayOf(1, WINDOW_SIZE.toLong(), CHANNELS.toLong()))
        val logits = module.forward(EValue.from(input))[0].toTensor().dataAsFloatArray
        var best = 0
        for (i in logits.indices) if (logits[i] > logits[best]) best = i
        return LABELS[best]
    }
}
"""


def buildReadme(model, executorch_version, bakes_features):
    features_note = " and feature extraction" if bakes_features else ""
    return (
        _README.replace("__MODEL_NAME__", model.name)
        .replace("__EXECUTORCH_VERSION__", executorch_version)
        .replace("__FEATURES_NOTE__", features_note)
    )


def buildKotlinExample(model, window_size, stride, num_classes):
    # Clamp to the labels that map to an actual output logit (see manifest.py):
    # this array indexes predictions on-device, so extra names would mislabel.
    labels = ", ".join(f'"{x.name}"' for x in model.labels[:num_classes])
    return (
        _KOTLIN.replace("__MODEL_NAME__", model.name)
        .replace("__TIMESERIES__", ", ".join(model.timeSeries))
        .replace("__WINDOW_SIZE__", str(window_size))
        .replace("__STRIDE__", str(stride))
        .replace("__CHANNELS__", str(len(model.timeSeries)))
        .replace("__LABELS__", labels)
    )
